### ISSUE TITLE
Microphone issue on GCP VM 

### ISSUE THREAD

**Issue by Meet-Fefar** [livekit/agents-playground#71]
### Instead it directly giving me this below error
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'getUserMedia')
Source
src/components/playground/Playground.tsx (73:24) @ setMicrophoneEnabled

at this line
```
  71 |     if (roomState === ConnectionState.Connected) {
  72 |       localParticipant.setCameraEnabled(config.settings.inputs.camera);
> 73 |       localParticipant.setMicrophoneEnabled(config.settings.inputs.mic);
     |                        ^
  74 |     }
  75 |   }, [config, localParticipant, roomState]);
  76 |
```

![error livekit playground](https://github.com/livekit/agents-playground/assets/80631754/7a45770e-48e8-4f57-bd0c-05b55c35c1c3)

### Reproduction

Deploying this app in GCP vm 
Perfromed Initial setup like setting up .env , 

Here is the config that i used

```
NEXT_PUBLIC_APP_CONFIG="
title: 'LiveKit Agent Playground'
description: 'LiveKit Agent Playground allows you to test your LiveKit Agent integration by connecting to your LiveKit Cloud or self-hosted instance.'
github_link: 'https://github.com/livekit/agents-playground'
video_fit: 'cover' # 'contain' or 'cover'
settings:
  editable: true # Should the user be able to edit settings in-app
  theme_color: 'cyan'
  chat: true  # Enable or disable chat feature
  outputs:
    audio: true # Enable or disable audio output
    video: false # Enable or disable video output
  inputs:
    mic: true    # Enable or disable microphone input
    camera: false # Enable or disable camera input
    sip: true    # Enable or disable SIP input
"
```

### System Info

```shell
System:
  OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
  CPU: (2) x64 Intel(R) Xeon(R) CPU @ 2.20GHz
  Memory: 1.49 GB / 1.91 GB
  Container: Yes
  Shell: 5.1.16 - /bin/bash
 Binaries:
  Node: 18.20.3 - /usr/bin/node
  npm: 10.7.0 - /usr/bin/npm
 npmPackages:
  livekit-client: ^2.1.5 => 2.2.0
```

### Severity

blocking all usage of LiveKit

### Additional Information

Feel Free to correct me if i made any mistakes
